#! /bin/sh

# Colors
. "${HOME}/.cache/wal/colors.sh"


#Default keyboard layout
setxkbmap us
xset r rate 150

#Mouse sensivity
xinput set-prop "SteelSeries SteelSeries Rival 110 Gaming Mouse" 306 -0.5

# Killing any possible previous processes
killall -q -w picom
killall -q -w sxhkd
killall -q -w polybar

sxhkd &
picom &
polybar -c=~/.config/polybar/bar mybar -r &
nitrogen --restore &
# Monitors
bspc monitor -d 1 2 3 4 5 6 7 8 9 0
./monitors.sh
# Mouse configs

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

# Settings
bspc config focused_border_color    "$color15"  
bspc config normal_border_color     "$color0"


#bspc config split_ratio          0.52
bspc config split_ratio          1.0
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
