live_config_reload = true

[[colors.indexed_colors]]
color = "0xf78c6c"
index = 16

[[colors.indexed_colors]]
color = "0xff5370"
index = 17

[[colors.indexed_colors]]
color = "0x303030"
index = 18

[[colors.indexed_colors]]
color = "0x353535"
index = 19

[[colors.indexed_colors]]
color = "0xb2ccd6"
index = 20

[[colors.indexed_colors]]
color = "0xeeffff"
index = 21

[colors.bright]
black = "#4c4c56"
blue = "#D694A8"
cyan = "#F0ABB4"
green = "#D28898"
magenta = "#EA99A6"
red = "#BC849C"
white = "#c3c3c6"
yellow = "#E6919D"

[colors.cursor]
cursor = "#c3c3c6"
text = "#c3c3c6"

[colors.normal]
black = "#11111e"
blue = "#D694A8"
cyan = "#F0ABB4"
green = "#D28898"
magenta = "#EA99A6"
red = "#BC849C"
white = "#c3c3c6"
yellow = "#E6919D"

[colors.primary]
background = "#11111e"
foreground = "#c3c3c6"

[env]
TERM = "alacritty"

[font]
size = 12

[font.bold]
family = "Cascadia Code"

[font.bold_italic]
family = "Cascadia Code"

[font.italic]
family = "Cascadia Code"

[font.normal]
family = "Cascadia Code"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[window.padding]
x = 10
y = 10
